export const DATA = [
    [
        {
            id: 1,
            description: "This beer is the rich color of honey with aromas of spectacularly malted barley and traditional herbal/floral hops. It also has a wee touch'o peeted malt which gives it a distinctive flavor that is rarely found in typical beers. If it's not Scottish its crap! (insert thick Scottish accent)",
            name: "Angus in Argyle",
            img: require("./assets/beverages/angusInArgyle.jpg"),
            style: "Scottish Peeted Golden Ale",
            type: "beverage",
        },
        {
            id: 2,
            abv: "5.5%",
            description: "The original classic India Pale Ale. Unlike its U.S. cousin this side of the pond, this traditional IPA is in complete balance between malt sweetness and hop bitterness. The flavor is reminiscent of eating a dense, moist fruit cake then rinsing your pallet clean with a dry and bitter sweet finale. It will leave your pallet beckoning for (as Ted used to say) more'ish. This beer is great on draft and spectacular at cellar temperature and pulled through a beer engine.",
            name: "Higgy Baby English",
            img: require("./assets/beverages/higgyBabyEnglish.jpg"),
            style: "IPA",
            type: "beverage",
        },
        {
            id: 3,
            abv: "7.2%",
            description: " Osage Orange IPA: Fruit forward IPA made with sweet orange peels and a wee bit o' brown sugar.",
            name: "Osage Orange",
            img: require("./assets/beverages/osageOrange.png"),
            style: "Orange IPA",
            type: "beverage",
        },
        {
            id: 4,
            abv: "4.4%",
            description: "Designed by our very own brewhouse minion/apprentice, Eric Shadowen. He wanted to create a Pale Lager that would be at home in the Southern Hemisphere, using only hops from New Zealand. We think he nailed it! We are serving this on cask or the dry hopped version on draught. A very smooth drinkin' malty-pale, leaning towards a fruit and flowery, hoppy presence.",
            name: "Zealander",
            img: require("./assets/beverages/zealander.png"),
            style: "Pale Lager",
            type: "beverage",
        },
    ],
    [
       {
            id: 1,
            description: "Brewer",
            img: require("./assets/brewery/brewery01.jpg"),
            type: "brewery",
        },
        {
            id: 2,
            description: "Brewing",
            img: require("./assets/brewery/brewery02.jpg"),
            type: "brewery",
        },
        {
            id: 3,
            description: "Out Front",
            img: require("./assets/brewery/brewery03.jpg"),
            type: "brewery",
        },
        {
            id: 4,
            description: "Growlers",
            img: require("./assets/brewery/brewery04.jpg"),
            type: "brewery",
        },
        {
            id: 5,
            description: "Shirts",
            img: require("./assets/brewery/brewery05.jpg"),
            type: "brewery",
        },
      {
            id: 6,
            description: "Taps",
            img: require("./assets/brewery/brewery06.jpg"),
            type: "brewery",
        },
        {
            id: 7,
            description: "Glass",
            img: require("./assets/brewery/brewery07.jpg"),
            type: "brewery",
        },
    ],
    [
       {
            id: 1,
            description: "Event 01",
            img: require("./assets/events/event01.jpg"),
            type: "event",
        },
       {
            id: 2,
            description: "Event 02",
            img: require("./assets/events/event02.png"),
            type: "event",
        },
        {
            id: 3,
            description: "Event 03",
            img: require("./assets/events/event03.png"),
            type: "event",
        },
        {
            id: 4,
            description: "Event 04",
            img: require("./assets/events/event04.jpg"),
            type: "event",
        },
       {
            id: 5,
            description: "Event 05",
            img: require("./assets/events/event05.png"),
            type: "event",
        },
        {
            id: 6,
            description: "Event 06",
            img: require("./assets/events/event06.jpg"),
            type: "event",
        },
    ],
    [
       {
            id: 1,
            description: "Taco",
            img: require("./assets/food/food01.jpg"),
            type: "food",
        },
       {
            id: 2,
            description: "Grilled Sandwich",
            img: require("./assets/food/food02.jpg"),
            type: "food",
        },
       {
            id: 3,
            description: "Fish n Chips",
            img: require("./assets/food/food03.jpg"),
            type: "food",
        },
        {
            id: 4,
            description: "Burger",
            img: require("./assets/food/food04.jpg"),
            type: "food",
        },
        {
            id: 5,
            description: "Wrap",
            img: require("./assets/food/food05.jpg"),
            type: "food",
        },
        {
            id: 6,
            description: "Roll",
            img: require("./assets/food/food06.jpg"),
            type: "food",
        },
        {
            id: 7,
            description: "Cup Cake",
            img: require("./assets/food/food07.jpg"),
            type: "food",
        },
        {
            id: 8,
            description: "Salad",
            img: require("./assets/food/food08.jpg"),
            type: "food",
        },
        {
            id: 9,
            description: "Bangers n Mash",
            img: require("./assets/food/food09.jpg"),
            type: "food",
        },
    ],
];

